version: '3.4'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: wolke
      POSTGRES_PASSWORD: wolke2024
      POSTGRES_DB: vcRiquinho
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432

  web:
    depends_on:
      - db
    image: tomcat-vcriquinho
    ports:
      - '8080:8080'
    environment:
      JAVA_POSTGRES_USER: wolke
      JAVA_POSTGRES_PASSWORD: wolke2024
      JAVA_POSTGRES_DB: vcRiquinho
volumes:
  postgres-db-volume: