volumes:
  dados:
  
networks:
 banco:
  
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
        - 5433:5432
    networks: 
      - banco
    volumes:
      #  Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: kaizenn/vcriquinho-web:latest
    ports:
      - 8080:8080
    networks: 
      - banco
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/vcriquinho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    depends_on:
      - db
