volumes:
  dados:
  
networks:
 banco:
  
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: admin
    ports:
        - 5433:5432
    networks: 
      - banco
    volumes:
      #  Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      JAVA_POSTGRES_USER: wolke
      JAVA_POSTGRES_PASSWORD: wolke2024
      JAVA_POSTGRES_DB: vcRiquinho
    depends_on:
      - db
