name: Build com Maven
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar mvn package install
        run: mvn package install

      - name: Executar testes
        run: mvn package install

      - name: Commit e push dos arquivos gerados
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add /target
          git commit -m "Adiciona arquivos gerados" -a
          git push

